petLost/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import routers
from rest_framework.permissions import AllowAny

from api.views import (
    AnnouncementViewSet, BannerViewSet, BreedViewSet, CityViewSet, CommentViewSet, PetViewSet, UserViewSet,
)

schema_view = get_schema_view(
   openapi.Info(
      title="Pet Lost",
      default_version='v1',
      description="Making Pets Happier",
      contact=openapi.Contact(email="guile.hm@hotmail.com"),
   ),
   public=True,
   permission_classes=(AllowAny,),
)

router = routers.DefaultRouter()
router.register(r'pets', PetViewSet)
router.register(r'breeds', BreedViewSet)
router.register(r'announcements', AnnouncementViewSet)
router.register(r'cities', CityViewSet)
router.register(r'users', UserViewSet)
router.register(r'banners', BannerViewSet)
router.register(r'comments', CommentViewSet)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('web.urls', namespace='web')),
    path('accounts/', include('allauth.urls')),
    path('api/', include(router.urls)),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns + static(
        prefix=settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )

web/urls.py
from django.urls import path

from web import views

app_name = 'web'

urlpatterns = [
    path('', views.index, name='index'),
    path('pets/lost/', views.lost_list, name='pet-lost'),
    path('pets/found/', views.found_list, name='pet-found'),
    path('pets/add/', views.pet_add, name='pet-add'),
    path('pets/owned/', views.pet_list_by_user, name='pet-owned-list'),
    path('pets/<str:slug>/', views.pet_detail, name='pet-detail'),
    path('pets/<str:slug>/change/', views.pet_change, name='pet-change'),
    path('pets/<str:slug>/pictures/upload/', views.pet_pictures_upload, name='pet-pictures-upload'),
    path(
        'pets/<str:slug>/pictures/remove/<int:picture_id>/',
        views.pet_pictures_remove, name='pet-pictures-remove'
    ),
    path(
        'pets/<str:slug>/pictures/profile/change/<int:picture_id>/',
        views.pet_pictures_profile_change, name='pet-pictures-profile-change'
    ),
    path('accounts/profile/', views.profile, name='account-profile'),
    path('accounts/profile/change', views.profile_change, name='account-profile-change'),
    path('accounts/login/', views.login_view, name='account-login'),
    path('accounts/logout/', views.logout_view, name='account-logout'),
    path('accounts/signup/', views.signup_view, name='account-signup'),
    path('accounts/social/login/cancelled/', views.login_view),
    path('announcements/add/', views.announcement_add, name='announcement-add'),
    path('emails/preview/<str:template>/', views.preview_email, name='preview-email'),
    path('comments/<int:comment_id>/delete/', views.comment_delete, name='comment-delete'),
]

users/models.py
from __future__ import unicode_literals

from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import PermissionsMixin
from django.core.mail import send_mail
from django.db import models
from django.utils.translation import ugettext_lazy as _

from web.utils import UploadToFactory


class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """
        Creates and saves a User with the given email and password.
        """
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_superuser', False)
        extra_fields.setdefault('is_staff', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_staff', True)
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(_('email address'), unique=True)
    first_name = models.CharField(_('first name'), max_length=30, blank=True)
    last_name = models.CharField(_('last name'), max_length=30, blank=True)
    date_joined = models.DateTimeField(_('date joined'), auto_now_add=True)
    is_active = models.BooleanField(_('active'), default=True)
    is_staff = models.BooleanField(
        _('staff'),
        default=False,
        help_text='Designates whether the user can log into this admin site.',
    )

    share_email = models.BooleanField(default=False)
    share_phone = models.BooleanField(default=False)
    phone_number = models.CharField(max_length=20, null=True, blank=True)
    mobile_phone_number = models.CharField(max_length=20, null=True, blank=True)
    org_name = models.CharField(_('organization name'), max_length=128, null=True, blank=True)
    profile_picture = models.ImageField(
        upload_to=UploadToFactory('users/user/profile-picture'),
        null=True,
        blank=True,
    )
    description = models.TextField(null=True, blank=True)

    postal_code = models.CharField(max_length=32, null=True, blank=True)
    address = models.CharField(max_length=256, null=True, blank=True)
    number = models.CharField(max_length=32, null=True, blank=True)
    complement = models.CharField(max_length=128, null=True, blank=True)
    district = models.CharField(max_length=128, null=True, blank=True)
    city = models.ForeignKey(
        'location.City',
        on_delete=models.SET_NULL,
        related_name='users',
        null=True,
        blank=True,
    )

    url_facebook_profile = models.URLField('Profile Facebook URL', null=True, blank=True)
    url_facebook_page = models.URLField('Page Facebook URL', null=True, blank=True)
    url_twitter = models.URLField('Twitter URL', null=True, blank=True)
    url_instagram = models.URLField('Instagram URL', null=True, blank=True)

    username = models.CharField(max_length=128, null=True, blank=True)

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def get_full_name(self):
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        send_mail(subject, message, from_email, [self.email], **kwargs)

    @property
    def get_address_data(self):
        return '{address}{number}{complement}{district}{city_data}'.format(
            address=f'{self.address}, ' if self.address else '',
            number=f'{self.number}, ' if self.number else '',
            complement=f'{self.complement}, ' if self.complement else '',
            district=f'{self.district}, ' if self.district else '',
            city_data=f'{self.city.data}' if self.city else '',
        )

web/templates/accounts/login.html
{% extends 'web/base.html' %}
{% load i18n %}
{% load static %}
{% block banners %}
    {% load socialaccount %}
    {% providers_media_js %}
    {% language 'pt-BR' %}
    <section class="home-slider owl-carousel">
        <div class="slider-item" style="background-image: url({% static 'web/img/login-banner-picture.jpg' %});">
            <div class="container">
                <div class="row slider-text align-items-center justify-content-center">
                    <div class="col-md-8 text-center col-sm-12 element-animate">
                        <div class="container text-center">
                        {% if messages %}
                            {% for message in messages %}
                                <div class="alert {% if message.tags == 'error' %}alert-danger{% else %}alert-info{% endif %} alert-dismissible fade show"
                                     role="alert">
                                    <strong>{{ message }}</strong>
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                            {% endfor %}
                        {% endif %}

                            {% if not request.user.is_authenticated %}
                                <form class="form-signin" method="post">
                                    {% csrf_token %}
                                    <h1 class="display-4 mb-2">Login</h1>
                                    {% for error in login_form.non_field_errors %}
                                        {{ error }}
                                    {% endfor %}
                                    <input type="text"
                                           class="form-control text-center mb-2"
                                           name="{{ login_form.email.name }}"
                                           placeholder="digite seu email"
                                           id="{{ login_form.email.id_for_label }}"
                                           {% if login_form.email.value != None %}value="{{ login_form.email.value|stringformat:'s' }}"{% endif %}
                                           maxlength="{{ login_form.email.field.max_length }}"
                                           {% if login_form.email.field.required %}required{% endif %}>

                                    {% for error in login_form.email.errors %}
                                        {{ error }}
                                    {% endfor %}
                                    <input type="password"
                                           class="form-control text-center mb-3"
                                           name="{{ login_form.password.name }}"
                                           placeholder="digite sua senha"
                                           id="{{ login_form.password.id_for_label }}"
                                           {% if login_form.password.value != None %}value="{{ login_form.password.value|stringformat:'s' }}"{% endif %}
                                           maxlength="{{ login_form.password.field.max_length }}"
                                           {% if login_form.password.field.required %}required{% endif %}>

                                    {% for error in login_form.password.errors %}
                                        {{ error }}
                                    {% endfor %}
                                    <button class="btn btn-lg btn-primary btn-block mb-3" type="submit">Entrar</button>
                                    <a href="{% provider_login_url "facebook" method="js_sdk" %}" class="btn btn-block btn-social btn-facebook mb-3"
                                       style="background-color:#3b5998;text-align:center">
                                        <span class="fa fa-facebook"></span>
                                        Entrar com Facebook
                                    </a>
                                    <a href="{% url 'web:account-signup' %}" class="">Ou cadastre-se aqui</a>
                                </form>
                            {% else %}
                                <h1 class="display-4 mb-2">Olá, {{ request.user.first_name }}, seja bem-vindo</h1>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    {% endlanguage %}
{% endblock %}
{% block content %}
{% endblock %}

web/templates/accounts/profile.html
{% extends 'web/base.html' %}
{% load i18n %}
{% load static %}
{% block headers %}
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
{% endblock %}
{% block banners %}
    {% load socialaccount %}
    {% providers_media_js %}
{% endblock %}
{% block content %}
<div class="div d-none d-xl-block" style="height: 80px; background-color: black;"></div>
<section class="section">
    <div class="container">
        {% if messages %}
            {% for message in messages %}
                <div class="alert {% if message.tags == 'error' %}alert-danger{% else %}alert-success{% endif %} alert-dismissible fade show mb-4" role="alert">
                    <strong>{{ message }}</strong>  {% if message.tags == 'error' %}Por favor revise todos os dados.{% endif %}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% endfor %}
        {% endif %}
        <div class="row">
            {% if change_form and personal_data_form or not change_form %}
            <div class="col-md-6 mb-5 order-2">
                <h2 class="heading mb-4">Dados Pessoais</h2>
                <form method="post">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-6 form-group">
                            <label for="first_name">Nome</label>
                            <input type="text" id="first_name" name="first_name" class="form-control" value="{{ user.first_name }}" {% if not personal_data_form %}disabled{% endif %} required>
                        </div>
                        <div class="col-md-6 form-group">
                            <label for="last_name">Sobrenome</label>
                            <input type="text" id="last_name" name="last_name" class="form-control " value="{{ user.last_name }}" {% if not personal_data_form %}disabled{% endif %}>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12 form-group">

                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12 form-group">
                            <label for="org_name">Organização</label>
                            <input type="text" id="org_name" name="org_name" class="form-control " value="{{ user.org_name|default:'' }}" {% if not personal_data_form %}disabled{% endif %}>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12 form-group">
                            <label for="description">Descrição</label>
                            <textarea name="description" id="description" class="form-control " cols="30" rows="4" {% if not personal_data_form %}disabled{% endif %}>{{ user.description|default:'' }}</textarea>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6 form-group">
                            {% if not personal_data_form %}
                                <a href="{% url 'web:account-profile-change' %}?personal_data=true" class="btn btn-primary">Editar</a>
                            {% else %}
                                <input type="submit" value="Salvar" class="btn btn-primary">
                            {% endif %}
                        </div>
                    </div>
                </form>
            </div>
            {% endif %}
            {% if change_form and contact_data_form or not change_form %}
            <div class="col-md-6 mb-5 order-2">
                <h2 class="heading mb-4">Contato</h2>
                <form method="post">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-6 form-group">
                            <label for="phone_number">Telefone Fixo</label>
                            <input type="text" id="phone_number" name="phone_number" class="form-control" value="{{ user.phone_number|default:'' }}" placeholder="Número com DDD" {% if not contact_data_form %}disabled{% endif %}>
                        </div>
                        <div class="col-md-6 form-group">
                            <label for="mobile_phone_number">Celular</label>
                            <input type="text" id="mobile_phone_number" name="mobile_phone_number" class="form-control " value="{{ user.mobile_phone_number|default:'' }}" placeholder="Número com DDD" {% if not contact_data_form %}disabled{% endif %}>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6 form-group">
                            <label for="share_phone">Compartilhar meus números?</label>
                            <input type="checkbox" id="share_phone" name="share_phone" class="form-control " {% if not contact_data_form %}value="{{ user.share_phone }}"{% endif %} style="height: 20px;" {% if user.share_phone %}checked{% endif %} {% if not contact_data_form %}onclick="return false;"{% endif %}>
                        </div>
                        <div class="col-md-6 form-group">
                            <label for="share_email">Compartilhar meu email?</label>
                            <input type="checkbox" id="share_email" name="share_email" class="form-control " {% if not contact_data_form %}value="{{ user.share_email }}"{% endif %} style="height: 20px;" {% if user.share_email %}checked{% endif %} {% if not contact_data_form %}onclick="return false;"{% endif %}>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12 form-group">
                            <label for="email">Email</label>
                            <input type="email" id="email" name="email" class="form-control " value="{{ user.email }}" disabled>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6 form-group">
                            {% if not contact_data_form %}
                                <a href="{% url 'web:account-profile-change' %}?contact_data=true" class="btn btn-primary">Editar</a>
                            {% else %}
                                <input type="submit" value="Salvar" class="btn btn-primary">
                            {% endif %}
                        </div>
                    </div>
                </form>
            </div>
            {% endif %}
        </div>
        <div class="row">
        {% if change_form and address_data_form or not change_form %}
            <div class="col-md-6 mb-5 order-2">
                <h2 class="heading mb-4">Endereço</h2>
                <form method="post">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-12 form-group">
                            <label for="address">Endereço</label>
                            <input type="text" id="address" name="address" class="form-control" value="{{ user.address|default:'' }}" {% if not address_data_form %}disabled{% endif %} required>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6 form-group">
                            <label for="number">Número</label>
                            <input type="text" id="number" name="number" class="form-control" value="{{ user.number|default:'' }}" {% if not address_data_form %}disabled{% endif %} required>
                        </div>
                        <div class="col-md-6 form-group">
                            <label for="complement">Complemento</label>
                            <input type="text" id="complement" name="complement" class="form-control " value="{{ user.complement|default:'' }}" {% if not address_data_form %}disabled{% endif %}>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6 form-group">
                            <label for="district">Bairro</label>
                            <input type="text" id="district" name="district" class="form-control " value="{{ user.district|default:'' }}" {% if not address_data_form %}disabled{% endif %} required>
                        </div>
                        <div class="col-md-6 form-group">
                            <label for="postal_code">Cep</label>
                            <input type="text" id="postal_code" name="postal_code" class="form-control" value="{{ user.postal_code|default:'' }}" {% if not address_data_form %}disabled{% endif %}>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-9 form-group">
                            <label for="city">Cidade</label>
                            {% if not address_data_form %}
                                <input type="text" id="city" name="city" class="form-control" value="{{ user.city.name|default:'' }}" disabled>
                            {% else %}
                                {{ address_data_form.city }}
                            {% endif %}
                        </div>
                        {% if not address_data_form %}
                        <div class="col-md-3 form-group">
                            <label for="state">Estado</label>
                                <input type="text" id="state" name="state" class="form-control" value="{{ user.city.state|default:'' }}" disabled>
                        </div>
                        {% endif %}
                    </div>
                    <div class="row">

                    </div>
                    <div class="row">
                        <div class="col-md-12 form-group">
                            {% if not address_data_form %}
                                <a href="{% url 'web:account-profile-change' %}?address_data=true" class="btn btn-primary">Editar</a>
                            {% else %}
                                <input type="submit" value="Salvar" class="btn btn-primary">
                            {% endif %}
                        </div>
                    </div>
                </form>
            </div>
            {% endif %}
            {% if change_form and social_media_data_form or not change_form %}
            <div class="col-md-6 mb-5 order-2">
                <h2 class="heading mb-4">Redes Sociais</h2>
                <form method="post">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-12 form-group">
                            <label for="url_facebook_profile">Perfil Facebook</label>
                            <input type="url" id="url_facebook_profile" name="url_facebook_profile" class="form-control" value="{{ user.url_facebook_profile|default:'' }}" {% if not social_media_data_form %}disabled{% endif %}>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12 form-group">
                            <label for="url_facebook_page">Página Facebook</label>
                            <input type="url" id="url_facebook_page" name="url_facebook_page" class="form-control" value="{{ user.url_facebook_page|default:'' }}" {% if not social_media_data_form %}disabled{% endif %}>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12 form-group">
                            <label for="url_twitter">Twitter</label>
                            <input type="url" id="url_twitter" name="url_twitter" class="form-control" value="{{ user.url_twitter|default:'' }}" {% if not social_media_data_form %}disabled{% endif %}>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12 form-group">
                            <label for="url_instagram">Instagram</label>
                            <input type="url" id="url_instagram" name="url_instagram" class="form-control" value="{{ user.url_instagram|default:'' }}" {% if not social_media_data_form %}disabled{% endif %}>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12 form-group">
                            {% if not social_media_data_form %}
                                <a href="{% url 'web:account-profile-change' %}?social_media_data=true" class="btn btn-primary">Editar</a>
                            {% else %}
                                <input type="submit" value="Salvar" class="btn btn-primary">
                            {% endif %}
                        </div>
                    </div>
                </form>
            </div>
            {% endif %}
        </div>
    </div>
</section>
{% endblock %}
{% block js %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#id_city').select2({
              theme: "classic"
            });
        });
    </script>
{% endblock %}

web/templates/accounts/signup.html
{% extends 'web/base.html' %}
{% load i18n %}
{% load static %}
{% block banners %}
    {% load socialaccount %}
    {% providers_media_js %}
    {% language 'pt-BR' %}
    <section class="home-slider owl-carousel">
        <div class="slider-item" style="background-image: url({% static 'web/img/login-banner-picture.jpg' %});">
            <div class="container">
                <div class="row slider-text align-items-center justify-content-center">
                    <div class="col-md-8 text-center col-sm-12 element-animate">
                        {% if messages %}
                            {% for message in messages %}
                                <div class="alert {% if message.tags == 'error' %}alert-danger{% else %}alert-info{% endif %} alert-dismissible fade show" role="alert">
                                    <strong>{{ message }}</strong>
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                            {% endfor %}
                        {% endif %}
                        <div class="container text-center">
                            {% if not request.user.is_authenticated %}
                                <form class="form-signin" method="post">
                                    {% csrf_token %}
                                    <h1 class="display-4 mb-2">Cadastro</h1>
                                    {% for error in form.non_field_errors %}
                                        {{ error }}
                                    {% endfor %}
                                    <input type="text"
                                           class="form-control text-center mb-2"
                                           name="{{ form.email.name }}"
                                           placeholder="digite seu email"
                                           id="{{ form.email.id_for_label }}"
                                           {% if form.email.value != None %}value="{{ form.email.value|stringformat:'s' }}"{% endif %}
                                           maxlength="{{ form.email.field.max_length }}"
                                           {% if form.email.field.required %}required{% endif %}>

                                    {% for error in form.email.errors %}
                                        {{ error }}
                                    {% endfor %}

                                    <input type="text"
                                           class="form-control text-center mb-2"
                                           name="{{ form.first_name.name }}"
                                           placeholder="digite seu nome"
                                           id="{{ form.first_name.id_for_label }}"
                                           {% if form.first_name.value != None %}value="{{ form.first_name.value|stringformat:'s' }}"{% endif %}
                                           maxlength="{{ form.first_name.field.max_length }}"
                                           {% if form.email.field.required %}required{% endif %}>

                                    {% for error in form.first_name.errors %}
                                        {{ error }}
                                    {% endfor %}

                                    <input type="password" name="password1" required id="id_password1" placeholder="digite sua senha" class="form-control text-center">
                                    <input type="password" name="password2" required id="id_password2" placeholder="repita sua senha" class="form-control text-center mb-3">

                                    <button class="btn btn-lg btn-primary btn-block mb-3" type="submit">Salvar</button>
                                    <a href="{% provider_login_url "facebook" method="js_sdk" %}" class="btn btn-block btn-social btn-facebook mb-3"
                                       style="background-color:#3b5998;text-align:center">
                                        <span class="fa fa-facebook"></span>
                                        Registrar com Facebook
                                    </a>
                                    <a href="{% url 'web:account-login' %}" class="">ou faça login aqui</a>
                                    {% block headers %}
                                        <script src='https://www.google.com/recaptcha/api.js'></script>
                                    {% endblock %}
                                    <br>
                                    <div class="g-recaptcha text-center mt-2" style="display: inline-block;" data-sitekey="{{ site_key }}"></div>
                                </form>
                            {% else %}
                                <h1 class="display-4 mb-2">Olá, {{ request.user.first_name }} seja bem-vindo</h1>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    {% endlanguage %}
{% endblock %}
{% block content %}
{% endblock %}