petLost/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import routers
from rest_framework.permissions import AllowAny

from api.views import (
    AnnouncementViewSet, BannerViewSet, BreedViewSet, CityViewSet, CommentViewSet, PetViewSet, UserViewSet,
)

schema_view = get_schema_view(
   openapi.Info(
      title="Pet Lost",
      default_version='v1',
      description="Making Pets Happier",
      contact=openapi.Contact(email="guile.hm@hotmail.com"),
   ),
   public=True,
   permission_classes=(AllowAny,),
)

router = routers.DefaultRouter()
router.register(r'pets', PetViewSet)
router.register(r'breeds', BreedViewSet)
router.register(r'announcements', AnnouncementViewSet)
router.register(r'cities', CityViewSet)
router.register(r'users', UserViewSet)
router.register(r'banners', BannerViewSet)
router.register(r'comments', CommentViewSet)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('web.urls', namespace='web')),
    path('accounts/', include('allauth.urls')),
    path('api/', include(router.urls)),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns + static(
        prefix=settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )

web/urls.py
from django.urls import path

from web import views

app_name = 'web'

urlpatterns = [
    path('', views.index, name='index'),
    path('pets/lost/', views.lost_list, name='pet-lost'),
    path('pets/found/', views.found_list, name='pet-found'),
    path('pets/add/', views.pet_add, name='pet-add'),
    path('pets/owned/', views.pet_list_by_user, name='pet-owned-list'),
    path('pets/<str:slug>/', views.pet_detail, name='pet-detail'),
    path('pets/<str:slug>/change/', views.pet_change, name='pet-change'),
    path('pets/<str:slug>/pictures/upload/', views.pet_pictures_upload, name='pet-pictures-upload'),
    path(
        'pets/<str:slug>/pictures/remove/<int:picture_id>/',
        views.pet_pictures_remove, name='pet-pictures-remove'
    ),
    path(
        'pets/<str:slug>/pictures/profile/change/<int:picture_id>/',
        views.pet_pictures_profile_change, name='pet-pictures-profile-change'
    ),
    path('accounts/profile/', views.profile, name='account-profile'),
    path('accounts/profile/change', views.profile_change, name='account-profile-change'),
    path('accounts/login/', views.login_view, name='account-login'),
    path('accounts/logout/', views.logout_view, name='account-logout'),
    path('accounts/signup/', views.signup_view, name='account-signup'),
    path('accounts/social/login/cancelled/', views.login_view),
    path('announcements/add/', views.announcement_add, name='announcement-add'),
    path('emails/preview/<str:template>/', views.preview_email, name='preview-email'),
    path('comments/<int:comment_id>/delete/', views.comment_delete, name='comment-delete'),
]

pet/models.py
import uuid

from django.db import models
from django.db.models import Q
from django.utils.functional import cached_property
from django.utils.text import slugify

from announcement.models import Announcement
from web.utils import UploadToFactory


class BreedQuerySet(models.QuerySet):
    def active(self):
        return self.filter(
            pets__isnull=False,
        )


class PetQuerySet(models.QuerySet):
    def lost(self):
        return self.filter(
            announcements__rescued=False,
            announcements__active=True,
            announcements__situation=Announcement.SITUATION_LOST,
        ).distinct()

    def found(self):
        return self.filter(
            announcements__rescued=False,
            announcements__active=True,
            announcements__situation=Announcement.SITUATION_FOUND,
        ).distinct()

    def rescued(self):
        return self.filter(
            announcements__rescued=True,
        ).distinct()

    def active(self):
        return self.filter(
            announcements__active=True,
        ).distinct()

    def not_active(self):
        return self.filter(
            Q(announcements__isnull=True) |
            Q(announcements__active__isnull=True)
        ).distinct()


class Breed(models.Model):
    TYPE_DOG = 'dog'
    TYPE_CHOICES = (
        (TYPE_DOG, 'Dog'),
    )
    name = models.CharField(max_length=128)
    kind = models.CharField(max_length=128, choices=TYPE_CHOICES, default=TYPE_DOG)
    slug = models.SlugField(db_index=True, unique=True)
    description = models.TextField(null=True, blank=True)

    date_added = models.DateTimeField(auto_now_add=True)
    date_changed = models.DateTimeField(auto_now=True)

    objects = BreedQuerySet.as_manager()

    def __str__(self):
        return f'{self.name}'


class Pet(models.Model):
    KIND_DOG = 'dog'
    KIND_CHOICES = (
        (KIND_DOG, 'Dog'),
    )

    SEX_MALE = 'male'
    SEX_FEMALE = 'female'
    SEX_NOT_IDENTIFIED = 'not_identified'
    SEX_CHOICES = (
        (SEX_MALE, 'Male'),
        (SEX_FEMALE, 'Female'),
        (SEX_NOT_IDENTIFIED, 'Not Identified'),
    )

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(
        'users.User',
        related_name='pets',
        on_delete=models.CASCADE,
    )
    name = models.CharField(max_length=128, null=True, blank=True)
    sex = models.CharField(max_length=32, choices=SEX_CHOICES)
    kind = models.CharField(max_length=128, choices=KIND_CHOICES, default=KIND_DOG)
    slug = models.SlugField(db_index=True, unique=True)
    breed = models.ForeignKey(
        'pet.Breed', related_name='pets', on_delete=models.CASCADE, null=True
    )
    picture = models.ForeignKey(
        'pet.Picture', null=True, blank=True, on_delete=models.SET_NULL
    )
    pictures = models.ManyToManyField('pet.Picture', related_name='pets', blank=True)
    description = models.TextField(null=True, blank=True)

    date_added = models.DateTimeField(auto_now_add=True)
    date_changed = models.DateTimeField(auto_now=True)

    objects = PetQuerySet.as_manager()

    def __str__(self):
        return f'{self.kind} #{str(self.id)[:8]} ({self.name})'

    @cached_property
    def announcement(self):
        return self.announcements.filter(active=True).last()

    @property
    def public_id(self):
        text = "{pet_name}-{kind}-{breed}-{id}".format(
            pet_name=self.name,
            kind=self.kind,
            breed=self.breed.name,
            id=str(self.id)[:5],
        )
        return slugify(text)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = self.public_id
        super().save(*args, **kwargs)


class Picture(models.Model):
    original_file_name = models.CharField(max_length=1024, null=True, blank=True)
    title = models.CharField(max_length=512, null=True, blank=True)
    image = models.ImageField(upload_to=UploadToFactory('pet/picture/image'))

    date_added = models.DateTimeField(auto_now_add=True)
    date_changed = models.DateTimeField(auto_now=True, db_index=True)

    def __str__(self):
        return '#{id}{title}'.format(
            id=self.id,
            title=f' ({self.title})' if self.title else '',
        )

    class Meta:
        ordering = ('date_changed', )

web/templates/web/tags/google_analytics.html
{% if google_analytics_id %}
    <script async src="https://www.googletagmanager.com/gtag/js?id={{ google_analytics_id}}"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', '{{ google_analytics_id }}');
    </script>
{% endif %}

web/templates/web/tags/home_slider.html
<section class="home-slider owl-carousel">
    {%  for banner in banners %}
        <div class="slider-item" style="background-image: url({{ banner.picture.url }});">
            <div class="container">
                <div class="row slider-text align-items-center justify-content-center">
                    <div class="col-md-8 text-center col-sm-12 element-animate">
                        <h1>{{ banner.title|default:'' }}</h1>
                        <p class="mb-5">{{ banner.subtitle|default:'' }}</p>
                        {% block messages %}
                            {% if messages %}
                                {% for message in messages %}
                                    <div class="alert alert-info alert-dismissible fade show" role="alert">
                                        <strong>{{ message }}</strong>
                                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                {% endfor %}
                            {% endif %}
                        {% endblock %}
                        <p>
                            {% if banner.button_one %}
                                <a href="{{ banner.button_one_link|default:'' }}" class="btn btn-white btn-outline-white">{{ banner.button_one|default:'' }}</a>
                            {% endif %}
                            {% if banner.button_two %}
                                <a href="{{ banner.button_two_link|default:'' }}" class="btn btn-link btn-white">{{ banner.button_two|default:'' }}</a>
                            {% endif %}
                        </p>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
</section>

web/templates/web/tags/pet_list.html
{% load static %}
{% load web_tags %}
{% block facebook_sdk %}
    <div id="fb-root"></div>
    <script async defer
            src="https://connect.facebook.net/pt_BR/sdk.js#xfbml=1&version=v3.2&appId=1986939548034882&autoLogAppEvents=1"></script>
{% endblock %}
<div class="row">
    {% for pet in pets %}
        <div class="col-md-6">
            <div class="media mb-4 d-md-flex d-block element-animate">
                {% if pet.picture %}
                    <a class="mr-5"><img src="{{ pet.picture.image.url }}" alt="{{ pet.slug }}" class="img-fluid"></a>
                {% else %}
                    <a class="mr-5"><img src="{% static 'web/img/placeholder.png' %}" alt="{{ pet.slug }}" class="img-fluid"></a>
                {% endif %}
                <div class="media-body">
                    <span class="post-meta">{{ pet.announcement.date_changed.date }}</span>
                    <h3 class="mt-2 text-black"><a href="{% url 'web:pet-detail' pet.slug %}">{{ pet.name|default:'Não Identificado' }}</a></h3>
                    <p>
                        {% if pet.announcement.situation == 'lost' %}
                            Desaparecido em: <strong>{{ pet.announcement.lost_date|date:'d/m/Y' }}</strong><br>
                        {% elif pet.announcement.situation == 'found' %}
                            Encontrado em: <strong>{{ pet.announcement.found_date|date:'d/m/Y' }}</strong><br>
                        {% endif %}
                        Local: <strong>{{ pet.announcement.last_seen_city.data }}</strong><br>
                        Sexo: <strong>{{ pet.get_sex_display|translation }}</strong><br>
                        Raça: <strong>{{ pet.breed }}</strong><br>
                        Status: <strong>{% if pet.announcement.rescued %}Resgatado{% else %}Não resgatado{% endif %}</strong><br>
                        {% if pet.announcement.description %}
                            <br>
                            {% if pet.announcement.description|length > 80 %}
                                Mensagem: {{ pet.announcement.description|slice:':80' }}...
                            {% else %}
                                Mensagem: {{ pet.announcement.description }}
                            {% endif %}
                        {% endif %}
                    </p>

                    <div class="fb-share-button mb-1" data-href="{% url 'web:pet-detail' pet.slug %}" data-layout="button_count" data-size="small" data-mobile-iframe="true"><a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u={% url 'web:pet-detail' pet.slug %};src=sdkpreparse" class="fb-xfbml-parse-ignore">Compartilhar</a></div>
                    <br>
                    <a class="twitter-share-button"
                               href="https://twitter.com/intent/tweet?{{ pet.announcement.share_description_encoded }}&url={% url 'web:pet-detail' pet.slug %}" target="_blank">
                                Tweet</a>
                    <p><a href="{% url 'web:pet-detail' pet.slug %}" class="btn btn-primary btn-sm">detalhes</a></p>
                </div>
            </div>
        </div>
    {% endfor %}
</div>