petLost/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import routers
from rest_framework.permissions import AllowAny

from api.views import (
    AnnouncementViewSet, BannerViewSet, BreedViewSet, CityViewSet, CommentViewSet, PetViewSet, UserViewSet,
)

schema_view = get_schema_view(
   openapi.Info(
      title="Pet Lost",
      default_version='v1',
      description="Making Pets Happier",
      contact=openapi.Contact(email="guile.hm@hotmail.com"),
   ),
   public=True,
   permission_classes=(AllowAny,),
)

router = routers.DefaultRouter()
router.register(r'pets', PetViewSet)
router.register(r'breeds', BreedViewSet)
router.register(r'announcements', AnnouncementViewSet)
router.register(r'cities', CityViewSet)
router.register(r'users', UserViewSet)
router.register(r'banners', BannerViewSet)
router.register(r'comments', CommentViewSet)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('web.urls', namespace='web')),
    path('accounts/', include('allauth.urls')),
    path('api/', include(router.urls)),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns + static(
        prefix=settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )

web/urls.py
from django.urls import path

from web import views

app_name = 'web'

urlpatterns = [
    path('', views.index, name='index'),
    path('pets/lost/', views.lost_list, name='pet-lost'),
    path('pets/found/', views.found_list, name='pet-found'),
    path('pets/add/', views.pet_add, name='pet-add'),
    path('pets/owned/', views.pet_list_by_user, name='pet-owned-list'),
    path('pets/<str:slug>/', views.pet_detail, name='pet-detail'),
    path('pets/<str:slug>/change/', views.pet_change, name='pet-change'),
    path('pets/<str:slug>/pictures/upload/', views.pet_pictures_upload, name='pet-pictures-upload'),
    path(
        'pets/<str:slug>/pictures/remove/<int:picture_id>/',
        views.pet_pictures_remove, name='pet-pictures-remove'
    ),
    path(
        'pets/<str:slug>/pictures/profile/change/<int:picture_id>/',
        views.pet_pictures_profile_change, name='pet-pictures-profile-change'
    ),
    path('accounts/profile/', views.profile, name='account-profile'),
    path('accounts/profile/change', views.profile_change, name='account-profile-change'),
    path('accounts/login/', views.login_view, name='account-login'),
    path('accounts/logout/', views.logout_view, name='account-logout'),
    path('accounts/signup/', views.signup_view, name='account-signup'),
    path('accounts/social/login/cancelled/', views.login_view),
    path('announcements/add/', views.announcement_add, name='announcement-add'),
    path('emails/preview/<str:template>/', views.preview_email, name='preview-email'),
    path('comments/<int:comment_id>/delete/', views.comment_delete, name='comment-delete'),
]

announcement/models.py
from django.core.exceptions import ValidationError
from django.db import models
from django.utils import timezone
from django.utils.http import urlencode


class CommentQuerySet(models.QuerySet):
    def active(self):
        return self.filter(deleted=False)


class Announcement(models.Model):
    SITUATION_LOST = 'lost'
    SITUATION_FOUND = 'found'
    SITUATION_CHOICES = (
        (SITUATION_LOST, 'Lost'),
        (SITUATION_FOUND, 'Found'),
    )

    active = models.BooleanField(default=True)
    pet = models.ForeignKey(
        'pet.Pet',
        related_name='announcements',
        on_delete=models.CASCADE,
    )
    situation = models.CharField(max_length=128, choices=SITUATION_CHOICES)
    description = models.TextField()

    rescued = models.BooleanField(default=False)
    rescued_date = models.DateField(null=True, blank=True)

    last_seen_district = models.CharField(max_length=512)
    last_seen_city = models.ForeignKey(
        'location.City', related_name='announcements', db_index=True, on_delete=models.CASCADE
    )

    lost_date = models.DateField(db_index=True, null=True, blank=True)
    found_date = models.DateField(db_index=True, null=True, blank=True)

    date_added = models.DateTimeField(auto_now_add=True)
    date_changed = models.DateTimeField(auto_now=True)

    def __str__(self):
        return '#{id}{pet}'.format(
            id=self.id,
            pet=f' ({self.pet.name})' if self.pet.name else 'Unknown',
        )

    def clean(self):
        if not hasattr(self, 'pet'):
            raise ValidationError('Please, choose a pet')

        if self.active:
            if self.pet.announcements.filter(
                    active=True,
            ).exclude(
                id=self.id
            ).exists():
                raise ValidationError('A pet may not have more than one active announcement')

        if not any([self.lost_date, self.found_date]):
            raise ValidationError('Lost Date or Found Date must be filled')

        if self.lost_date and not self.pet.name:
            raise ValidationError('Please fill the name of your pet')

        if not self.situation:
            if self.found_date:
                self.situation = self.SITUATION_FOUND
            elif self.lost_date:
                self.situation = self.SITUATION_LOST

        if self.rescued and not self.rescued_date:
            self.rescued_date = timezone.now()

    def get_comments(self):
        return self.comments.filter(deleted=False)

    def save(self, *args, **kwargs):
        self.clean()
        return super().save(*args, **kwargs)

    @property
    def share_description(self):
        return 'PetLost - Ajude {name} encontrar sua família. El{sex} conta com a sua ajuda!'.format(
            name=self.pet.name or 'este cãozinho a',
            sex='a' if self.pet.sex == self.pet.SEX_FEMALE else 'e',
        )

    @property
    def share_description_encoded(self):
        description = self.share_description
        return urlencode({'text': description})

    @property
    def lost_description(self):
        lost_description = ''
        if self.situation == self.SITUATION_LOST:
            text = f'Eu desapareci no dia {self.lost_date.strftime("%d/%m/%Y")}.\n'
            lost_description += text
        elif self.situation == self.SITUATION_FOUND:
            text = 'Fui encontrad{sex} no dia {date}.\n'.format(
                sex='a' if self.pet.sex == self.pet.SEX_FEMALE else 'o',
                date=self.found_date.strftime("%d/%m/%Y")
            )
            lost_description += text
        text = f'Me viram por último em {self.last_seen_city.data}.\n'
        lost_description += text
        if self.pet.sex == self.pet.SEX_NOT_IDENTIFIED:
            text = 'Ainda não identificaram meu sexo.'
        elif self.pet.sex == self.pet.SEX_MALE:
            text = 'Sou um macho.'
        elif self.pet.sex == self.pet.SEX_FEMALE:
            text = 'Sou uma fêmea.'
        lost_description += f'{text}\n'
        if not self.rescued:
            text = 'Ainda não encontrei minha família, conto com sua ajuda para encontrá-los.'
        else:
            text = f'Fui recuperado por minha família em ' \
                f'{self.rescued_date.strftime("%d/%m/%Y")} graças à ajuda de pessoas como você.'
        lost_description += text
        return lost_description


class Comment(models.Model):
    announcement = models.ForeignKey(
        'announcement.Announcement',
        related_name='comments',
        on_delete=models.CASCADE,
    )
    user = models.ForeignKey(
        'users.User',
        related_name='comments',
        on_delete=models.CASCADE,
    )
    deleted = models.BooleanField(default=False)
    description = models.CharField(max_length=512)

    date_added = models.DateTimeField(auto_now_add=True)
    date_changed = models.DateTimeField(auto_now=True)

    objects = CommentQuerySet.as_manager()

    def __str__(self):
        return '{}{}'.format(
            self.description[:50],
            '' if len(self.description) <= 50 else '...',
        )

pet/models.py
import uuid

from django.db import models
from django.db.models import Q
from django.utils.functional import cached_property
from django.utils.text import slugify

from announcement.models import Announcement
from web.utils import UploadToFactory


class BreedQuerySet(models.QuerySet):
    def active(self):
        return self.filter(
            pets__isnull=False,
        )


class PetQuerySet(models.QuerySet):
    def lost(self):
        return self.filter(
            announcements__rescued=False,
            announcements__active=True,
            announcements__situation=Announcement.SITUATION_LOST,
        ).distinct()

    def found(self):
        return self.filter(
            announcements__rescued=False,
            announcements__active=True,
            announcements__situation=Announcement.SITUATION_FOUND,
        ).distinct()

    def rescued(self):
        return self.filter(
            announcements__rescued=True,
        ).distinct()

    def active(self):
        return self.filter(
            announcements__active=True,
        ).distinct()

    def not_active(self):
        return self.filter(
            Q(announcements__isnull=True) |
            Q(announcements__active__isnull=True)
        ).distinct()


class Breed(models.Model):
    TYPE_DOG = 'dog'
    TYPE_CHOICES = (
        (TYPE_DOG, 'Dog'),
    )
    name = models.CharField(max_length=128)
    kind = models.CharField(max_length=128, choices=TYPE_CHOICES, default=TYPE_DOG)
    slug = models.SlugField(db_index=True, unique=True)
    description = models.TextField(null=True, blank=True)

    date_added = models.DateTimeField(auto_now_add=True)
    date_changed = models.DateTimeField(auto_now=True)

    objects = BreedQuerySet.as_manager()

    def __str__(self):
        return f'{self.name}'


class Pet(models.Model):
    KIND_DOG = 'dog'
    KIND_CHOICES = (
        (KIND_DOG, 'Dog'),
    )

    SEX_MALE = 'male'
    SEX_FEMALE = 'female'
    SEX_NOT_IDENTIFIED = 'not_identified'
    SEX_CHOICES = (
        (SEX_MALE, 'Male'),
        (SEX_FEMALE, 'Female'),
        (SEX_NOT_IDENTIFIED, 'Not Identified'),
    )

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(
        'users.User',
        related_name='pets',
        on_delete=models.CASCADE,
    )
    name = models.CharField(max_length=128, null=True, blank=True)
    sex = models.CharField(max_length=32, choices=SEX_CHOICES)
    kind = models.CharField(max_length=128, choices=KIND_CHOICES, default=KIND_DOG)
    slug = models.SlugField(db_index=True, unique=True)
    breed = models.ForeignKey(
        'pet.Breed', related_name='pets', on_delete=models.CASCADE, null=True
    )
    picture = models.ForeignKey(
        'pet.Picture', null=True, blank=True, on_delete=models.SET_NULL
    )
    pictures = models.ManyToManyField('pet.Picture', related_name='pets', blank=True)
    description = models.TextField(null=True, blank=True)

    date_added = models.DateTimeField(auto_now_add=True)
    date_changed = models.DateTimeField(auto_now=True)

    objects = PetQuerySet.as_manager()

    def __str__(self):
        return f'{self.kind} #{str(self.id)[:8]} ({self.name})'

    @cached_property
    def announcement(self):
        return self.announcements.filter(active=True).last()

    @property
    def public_id(self):
        text = "{pet_name}-{kind}-{breed}-{id}".format(
            pet_name=self.name,
            kind=self.kind,
            breed=self.breed.name,
            id=str(self.id)[:5],
        )
        return slugify(text)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = self.public_id
        super().save(*args, **kwargs)


class Picture(models.Model):
    original_file_name = models.CharField(max_length=1024, null=True, blank=True)
    title = models.CharField(max_length=512, null=True, blank=True)
    image = models.ImageField(upload_to=UploadToFactory('pet/picture/image'))

    date_added = models.DateTimeField(auto_now_add=True)
    date_changed = models.DateTimeField(auto_now=True, db_index=True)

    def __str__(self):
        return '#{id}{title}'.format(
            id=self.id,
            title=f' ({self.title})' if self.title else '',
        )

    class Meta:
        ordering = ('date_changed', )

web/templates/web/base.html
{% load static %}
{% load web_tags %}
<!doctype html>
<html lang="pt-BR">
<head>
    {% google_analytics %}
    {% block title %}
    <title>PetLost - Ajude um pet a encontrar sua família</title>
    {% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="google-site-verification" content="83fcqoPn-YTkXathQiicW-x3U2RWZh4PaPUzk91wtjY" />
    {% block meta %}
    {% endblock %}
    <link rel="shortcut icon" href="{% static 'web/img/favicon.ico' %}" type="image/x-icon">
    <link rel="icon" href="{% static 'web/img/favicon.ico' %}" type="image/x-icon">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700,800" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'web/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'web/css/animate.css' %}">
    <link rel="stylesheet" href="{% static 'web/css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'web/fonts/ionicons/css/ionicons.min.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'web/css/style.css' %}">
    {% block headers %}
    {% endblock %}
</head>
<body>
{% block facebook_sdk %}
{% endblock %}
<header role="banner">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand absolute" href="{% url 'web:index' %}">Pet Lost</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbars05"
                    aria-controls="navbars05" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbars05">
                <ul class="navbar-nav mx-auto pl-lg-5 pl-0">
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'web:pet-lost' %}">Desaparecidos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'web:pet-found' %}">Encontrados</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'web:announcement-add' %}">Anuncie Grátis</a>
                    </li>
                </ul>
                <ul class="navbar-nav ml-auto pl-lg-5 pl-0">
                    {% if not request.user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link active" href="{% url 'web:account-login' %}">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" href="{% url 'web:account-signup' %}">Registrar</a>
                        </li>
                    {% else %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="services.html" id="dropdown04" data-toggle="dropdown" aria-haspopup="true"
                               aria-expanded="false">Minha Conta</a>
                            <div class="dropdown-menu" aria-labelledby="dropdown04">
                                {% if request.user.socialaccount_set.exists %}
                                    <img src="{{ request.user.socialaccount_set.all.0.get_avatar_url }}" class="img-fluid d-sm-none d-md-block " alt="">
                                {% endif %}
                                <a class="dropdown-item" href="{% url 'web:account-profile' %}">Perfil</a>
                                <a class="dropdown-item" href="{% url 'web:pet-owned-list' %}">Meus Pets</a>
                                <a class="dropdown-item" href="{% url 'web:account-logout' %}">Logout</a>
                            </div>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
</header>
<!-- END header -->
{% block banners %}
{% banners request %}
{% endblock %}
{% block content %}
{% endblock %}

{% block footer %}
<footer class="site-footer" role="contentinfo">
    <div class="container">
        <div class="row mb-5">
            <div class="col-md-4 mb-5">
                <h3>Sobre a PetLost</h3>
                <p class="mb-5">Queremos ajudar os animais a encontrarem suas famílias.</p>
            </div>
            <div class="col-md-5 mb-5">
                <h3>Dados para Contato</h3>
                <ul class="list-unstyled footer-link">
                    <li class="d-block"><span class="d-block">Email:</span>
                        <span class="text-white">guile.hm@hotmail.com</span>
                    </li>
                </ul>
            </div>
            <div class="col-md-3 mb-5">
                <h3>Quick Links</h3>
                <ul class="list-unstyled footer-link">
                    <li><a href="{% url 'web:pet-lost' %}">Desaparecidos</a></li>
                    <li><a href="{% url 'web:pet-found' %}">Encontrados</a></li>
                </ul>
            </div>
            <div class="col-md-3">

            </div>
        </div>
        <div class="row">
            <div class="col-12 text-md-center text-left">
                    desenvolvido por
                    <a href="https://github.com/Guilehm/" target="_blank">guilherme luis</a></p>
            </div>
        </div>
    </div>
</footer>
<!-- END footer -->
{% endblock %}

<!-- loader -->
<div id="loader" class="show fullscreen">
    <svg class="circular" width="48px" height="48px">
        <circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/>
        <circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10"stroke="#f4b214"/>
    </svg>
</div>

<script src="{% static 'web/js/jquery-3.2.1.min.js' %}"></script>
<script src="{% static 'web/js/popper.min.js' %}"></script>
<script src="{% static 'web/js/bootstrap.min.js' %}"></script>
<script src="{% static 'web/js/owl.carousel.min.js' %}"></script>
<script src="{% static 'web/js/jquery.waypoints.min.js' %}"></script>
<script src="{% static 'web/js/main.js' %}"></script>
{% block js %}
{% endblock %}
</body>
</html>

web/templates/web/pet_detail.html
{% extends 'web/base.html' %}
{% load static %}
{% block content %}
{% block meta %}
    <meta property="og:url" content="{{ request.build_absolute_uri }}"/>
    <meta property="og:type" content="website"/>
    <meta property="og:description" content="{{ pet.announcement.lost_description }}"/>
    {% if not pet.name %}
        <meta property="og:title" content="PetLost - Ajude um pet a encontrar sua família"/>
    {% else %}
        <meta property="og:title" content="{{ pet.announcement.share_description }}"/>
    {% endif %}
    {% if pet.picture %}
        <meta property="og:image" content="{{ pet.picture.image.url }}" />
        <meta name="twitter:image" content="{{ pet.picture.image.url }}">
    {% else %}
        <meta property="og:image" content="{% static 'web/img/placeholder.png' %}" />
    {% endif %}
{% endblock %}
{% block headers %}
    <link rel="stylesheet" href="{% static 'web/css/basic.css' %}">
    <link rel="stylesheet" href="{% static 'web/css/dropzone.css' %}">
    <script src="{% static 'web/js/dropzone.js' %}"></script>
{% endblock %}
{% block facebook_sdk %}
    <div id="fb-root"></div>
    <script async defer
            src="https://connect.facebook.net/pt_BR/sdk.js#xfbml=1&version=v3.2&appId=1986939548034882&autoLogAppEvents=1"></script>
{% endblock %}
{% block banners %}
{% endblock %}
    <style>
        .comment-wrapper .panel-body {
            max-height:650px;
            overflow:auto;
        }

        .comment-wrapper .media-list .media img {
            width:64px;
            height:64px;
            border:2px solid #e5e7e8;
        }

        .comment-wrapper .media-list .media {
            border-bottom:1px dashed #efefef;
            margin-bottom:25px;
        }
    </style>
<div class="div d-none d-xl-block" style="height: 80px; background-color: black;"></div>
<section class="section element-animate">
    <div class="container">
        {% if messages %}
            {% for message in messages %}
                <div class="alert {% if message.tags == 'error' %}alert-danger{% else %}alert-info{% endif %} alert-dismissible fade show" role="alert">
                    <strong>{{ message }}</strong>
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% endfor %}
        {% endif %}
        <div class="row justify-content-center mb-5">
            <div class="col-md-4"></div>
            <div class="col-md-8 section-heading">
                <h2>{{ pet.name|default:'Não Identificado' }}</h2>
                {% if pet.announcement %}
                    {% if not pet.announcement.rescued %}
                        {% if pet.announcement.situation == 'lost' %}
                            <p class="small-sub-heading">Ainda estou desaparecid{% if pet.sex == 'female' %}a{% else  %}o{% endif %}</p>
                        {% else %}
                            <p class="small-sub-heading">Ainda estou procurando minha família</p>
                        {% endif %}
                    {% else %}
                        <p class="small-sub-heading">já encontrei minha família :)</p>
                    {% endif %}
                {% endif %}
            </div>
        </div>
        <div class="row">
            <div class="col-md-4 mb-4">
                {% if pet.picture %}
                    <img src="{{ pet.picture.image.url }}" alt="{{ pet.slug }}" class="img-fluid">
                {% else %}
                    <img src="{% static 'web/img/placeholder.png' %}" alt="{{ pet.slug }}" class="img-fluid">
                {% endif %}
                {% if owner %}
                    <br>
                    <a class="text-dark" href="{% url 'web:pet-change' pet.slug %}">editar cadastro</a>
                {% endif %}
            </div>
            {% if pet.announcement %}
                <div class="col-md-4">
                    <strong>Um pouco sobre mim:</strong> <br>
                    <p>{{ pet.announcement.lost_description|linebreaks }}</p>
                    {% if not pet.announcement.rescued %}
                    <p>
                        <button class="btn btn-success btn-sm">alguma informação sobre mim?</button>
                    </p>
                    {% endif %}
                </div>
            {% endif %}
            <div class="col-md-4">
                {% if pet.description %}
                    <p><strong>O que minha família disse sobre mim:</strong> <br> {{ pet.description|default:'' }}</p>
                {% endif %}
                {% if pet.announcement.description %}
                    <p><strong>Descrição do anúncio:</strong> <br> {{ pet.announcement.description|default:'' }}</p>
                {% endif %}
                {% if not pet.announcement.rescued %}
                    <p><a class="font-weight-bold">Compartilhe</a></p>
                    <ul class="list-unstyled">
                        <li>
                            <div class="fb-share-button" data-href="{{ request.build_absolute_uri }}" data-layout="button_count" data-size="small" data-mobile-iframe="true"><a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u={{ request.build_absolute_uri }};src=sdkpreparse" class="fb-xfbml-parse-ignore">Compartilhar</a></div>
                        </li>
                        <li>
                            <a class="twitter-share-button"
                               href="https://twitter.com/intent/tweet?{{ pet.announcement.share_description_encoded }}" target="_blank">
                                Tweet</a>
                        </li>
                    </ul>
                {% endif %}
            </div>
        </div>
    </div>
</section>
<section class="section border-t bg-white element-animate pt-0">
<div class="row bootstrap mx-0">
    <div class="container">
        <div class="col-md-offset-2 col-sm-12">
            <div class="comment-wrapper">
                <div class="panel panel-info">
                    <div class="panel-heading">
                        Comentários
                        {% if not user.is_authenticated %}
                            <a href="{% url 'web:account-login' %}">(faça login para comentar)</a>
                        {% endif %}
                    </div>
                    <div class="panel-body">
                    {% if user.is_authenticated %}
                        <form method="post">
                        {% csrf_token %}
                        <textarea required class="form-control" name="description" placeholder="escreva um comentário..." rows="3"></textarea>
                        <br>
                        <button type="submit" class="btn btn-success pull-right">Comentar</button>
                        </form>
                    {% endif %}
                        <div class="clearfix"></div>
                        <hr>
                        <ul class="media-list">
                            {% for comment in pet.announcement.get_comments %}
                                <li class="media">
                                    <a class="pull-left">
                                        {% if comment.user.socialaccount_set.exists %}
                                            <img src="{{ comment.user.socialaccount_set.all.0.get_avatar_url }}" alt="profile">
                                        {% else %}
                                            <img src="{% static 'web/img/avatar.png' %}" alt="profile" class="">
                                        {% endif %}
                                    </a>
                                    <div class="media-body">
                                        <span class="text-muted pull-right">
                                            <small class="text-muted">{{ comment.date_added }}</small><br>
                                            {% if comment.user == request.user %}
                                                <small class="text-muted float-right"><a href="{% url 'web:comment-delete' comment.id %}">deletar</a></small><br>
                                            {% endif %}
                                        </span>
                                        <strong class="text-success">{{ comment.user.first_name|default:'Não Identificado' }}</strong>
                                        <p>{{ comment.description }}</p>
                                    </div>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>
</section>

{% if pet.pictures.exists %}
<section class="section border-t bg-light">
    <div class="container">
        <div class="row justify-content-center mb-5 element-animate">
            <div class="col-md-8 text-center">
                <h2 class=" heading mb-4">Fotos</h2>
            </div>
        </div>

        <div class="row no-gutters">
            {% for picture in pet.pictures.all %}
                <div class="col-md-4 element-animate">
                    <a class="link-thumbnail">
                        <h3>{{ picture.title|default:'' }}</h3>
                        <img src="{{ picture.image.url }}" alt="{{ picture.title|default:'' }}" class="img-fluid">
                    </a>
                    {% if owner %}
                        <p class="text-center">
                            <a class="text-black px-3" href="{% url 'web:pet-pictures-remove' pet.slug picture.id %}">
                                <span class="fa fa-trash"></span>
                            </a>
                            <a class="text-black px-3"
                               href="{% url 'web:pet-pictures-profile-change' pet.slug picture.id %}">
                                <span class="fa fa-paw"></span>
                            </a>
                        </p>
                    {% endif %}
                </div>
            {% endfor %}
        </div>

    </div>
{% endif %}
</section>
{% if owner and pet.pictures.count < 10%}
<section class="section border-t">
    <div class="container">
        <div class="row justify-content-center mb-5 element-animate">
            <div class="col-md-12 text-center">
                <h2 class=" heading mb-4">
                    Adicione fotos
                    {% if pet.name %}
                        d{% if pet.sex == 'female' %}a{% else %}o{% endif %} {{ pet.name }}
                    {% endif %}
                </h2>
                <style>
                    .dropzone {
                        border: dashed 1px black;
                    }
                </style>
                <form action="{% url 'web:pet-pictures-upload' pet.slug %}" class="dropzone" id="dzone" enctype="multipart/form-data" method="post">
                    {% csrf_token %}
                </form>
            </div>
        </div>

    </div>
</section>
{% endif %}
{% if owner and not pet.announcement %}
<section class="section border-t">
    <div class="container">
        <div class="row justify-content-center mb-5 element-animate">
            <div class="col-md-12 text-center">
                <h2 class=" heading mb-4">
                    {{ pet.name }} está desaparecid{% if pet.sex == 'female' %}a{% else  %}o{% endif %}?
                </h2>

                <a class="btn btn-sm btn-success" href="{% url 'web:announcement-add' %}">Anuncie Grátis</a>
            </div>
        </div>
    </div>
</section>
{% endif %}
{% endblock %}
{% block js %}
    <script>window.twttr = (function (d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0],
            t = window.twttr || {};
        if (d.getElementById(id)) return t;
        js = d.createElement(s);
        js.id = id;
        js.src = "https://platform.twitter.com/widgets.js";
        fjs.parentNode.insertBefore(js, fjs);

        t._e = [];
        t.ready = function (f) {
            t._e.push(f);
        };

        return t;
    }(document, "script", "twitter-wjs"));
    </script>

    <script>
        Dropzone.options.dzone = {
            paramName: "image",
            maxFilesize: 2,
            maxFiles: 10,
            autoProcessQueue: true,
            acceptedFiles: "image/jpeg,image/png,image/jpg",
            dictDefaultMessage: "Arraste as imagens aqui ou clique para selecionar.",
            dictInvalidFileType: "Tipo de arquivo não permitido.",
            dictFileTooBig: "Tamanho do arquivo excede o limite de 2 mb.",
        };
    </script>

{% endblock %}